name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        registry: docker.io
        repository: skollnope/mywebserver
        tag_with_sha: true
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.4env
      env:
        GITHUB_TOKEN: ${{ secrets.skollnope }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

