name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        registry: docker.io
        repository: skollnope/mywebserver
        tag_with_sha: true
