name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: PMD Source Code Analyzer Action
      uses: sfdx-actions/setup-pmd@v1
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.skollnope }}
        password: ${{ secrets.playstation117 }}
        registry: docker.io
        repository: skollnope/mywebserver
        tag_with_sha: true
